#lang racket
(define (call-the-cops) 'ALARM)
(define (make-account balance password counter)
  (define (withdraw amount pass)
     (cond ((not (eq? pass password)) (if (< counter 7)
                                          (begin (set! counter (+ counter 1))
                                                 'Denied!)
                                          (call-the-cops)))
           ((>= balance amount) (begin (set! counter 0)
                                       (set! balance (- balance amount))
                                       balance))
           (else 'No-money)))
   (define (deposit amount pass)
     (cond ((not (eq? pass password)) (if (< counter 7)
                                          (begin (set! counter (+ counter 1))
                                                 'Denied!)
                                          (call-the-cops)))
           (else (begin (set! counter 0)
                        (set! balance (+ balance amount))
                        balance))))
   (define (dispatch symbol)
     (cond ((eq? symbol 'withdraw) withdraw)
           ((eq? symbol 'deposit) deposit)
           (else (error "No such op") symbol)))
   dispatch)

(provide (all-defined-out))
