#lang racket
(define (make-account balance password)
  (define (withdraw amount pass)
    (cond ((not (eq? pass password)) 'Denied!)
          ((>= balance amount) (begin (set! balance (- balance amount))
                                      balance))
          (else 'No-money)))
  (define (deposit amount pass)
    (cond ((not (eq? pass password)) 'Denied!)
          (else (set! balance (+ balance amount))
                balance)))
  (define (nullify password)
    (set! balance 0)
    balance)
  (define (dispatch symbol)
    (cond ((eq? symbol 'withdraw) withdraw)
          ((eq? symbol 'deposit) deposit)
          ((eq? symbol 'nullify) nullify)
          (else (error "No such op") symbol)))
  dispatch)
(define myaccount (make-account 1500 'gosha-noobik))

(provide make-account)